interface ResultProps {
  data: {
    prediction?: string;
    confidence?: number;
    K?:number;
    [key: string]: any;
  };
}

export default function ResultCard({ data }: ResultProps) {
  const { prediction, confidence,K} = data;
  console.log(prediction)
  return (
    <div className="mt-6 p-6 rounded-xl shadow-xl bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#0ea5e9] border border-gray-700 text-center text-white">
      <h2 className="text-2xl font-semibold mb-2 text-cyan-300">Prediction Result</h2>

      <p className="text-lg mb-3">
        This news appears to be:
        <span
          className={`ml-2 font-bold ${
            prediction === "FAKE"
              ? "text-red-400"
              : prediction === "REAL"
              ? "text-green-400"
              : "text-gray-300"
          }`}
        >
          {prediction || "Unknown"}
        </span>
      </p>

      {confidence !== undefined && (
        <p className="text-gray-200">
          Confidence: <span className="font-medium">{(confidence * 100).toFixed(2)}%</span>
        </p>
      )}
      
      <div className="mt-4 text-sm text-gray-300">
        {K === 0
          ? "(This result is generated by checking evidence)"
          : "(This result is generated by Fake News Detection model)"}
      </div>
    </div>
  );
}
